### ISSUE TITLE
Check for trusted host patterns and update BaseUrl description

### ISSUE THREAD

**Issue by bjeavons** [banviktor/security_review#18]
After reviewing [trusted_host_patterns](https://www.drupal.org/node/2410395) I think Security Review should include it as a check. The functionality could replicate what core does for the reports page but since this is a security hardening feature it's appropriate to list as part of the Security Review checklist.

There is a [issue for proposing $base_url be removed](https://www.drupal.org/node/2528988) so if that gets committed then it'd be appropriate to remove BaseUrl check.

In the mean time, how about making trusted host patterns check be hidden if BaseUrl check passes -- since setting base_url effectively limits hosts your Drupal site responds to. If BaseUrl check fails then also run the trusted host patterns check. 

BaseUrl help could mention trusted host pattern as a mitigation against the type of attack that BaseUrl also protects against.

**Comment by banviktor** [comment]
@bjeavons Could you help with the help and evaluation texts? I think your descriptions about the check would be a lot more usable. 
The new check will be done by friday (I'm focusing on the services atm, also won't be able to work much on wednesday, only in the evening).

**Comment by banviktor** [comment]
@bjeavons Hiding a check result based on another check's result requires knowledge of the sequence of the checks. We have knowledge of that (as it's explicitly sorted in Checklist), however I don't think it's a good idea using it.
The other solution is extending the Base URL check with the Trusted host patterns check, and when the said issue gets committed then remove the Base URL part and rename the check.

**Comment by banviktor** [comment]
@bjeavons The new check was added d19e344b52d17ca2fa4988a92c00e763bf343db1 without help and evaluation texts.
