### ISSUE TITLE
Move Check result and findings to State system

### ISSUE THREAD

**Issue by bjeavons** [banviktor/security_review#5]
While considering the options for #2 I read up on the Drupal 8 state system which I think is more applicable for Security Review Check results and findings than the Configuration system. 

State:

    It is specific to an individual environment.
    You will never want to deploy it between environments.
    You can reset a system, losing all state. Its configuration remains.

Those all hold true for Security Review check results and findings.

What do you think of removing security_review.check_result and security_review. check_findings * schema and implementing results and findings with the State system?

**Comment by banviktor** [comment]
That makes sense. The rest should remain in the Configuration system?

**Comment by banviktor** [comment]
Implemented in commit 72a1eb934ee74f875eba5e1a48f6bc7519b3cd92.
